// <auto-generated />
using Infrastructure.Persistence.CompiledModels;
using Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(ApplicationDbContext), typeof(ApplicationDbContextModel))]
